# Generated by Django 4.2.1 on 2023-05-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(null=True, upload_to='Imagens', verbose_name='imagem_noticia'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='link_imagem',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='link_video',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Thumbnail', verbose_name='Thumbnail'),
        ),
    ]
