# Generated by Django 4.2.1 on 2023-05-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemak', '0002_noticia_data_noticia_imagem_noticia_link_imagem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Rodapé'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
